theme: jekyll-theme-cayman
title: "Rimon Hamo" 'Ray'
description: “Driven technologist combining engineering precision with computer science innovation. Passionate about robotics, automation, and artificial intelligence that shape the future of human-machine collaboration.”
